[project]
name = "surun"
version = "2025.4.30.0"
description = "surun and related tools"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pywin32>=310",
    "sodatools>=2025.2.16.0",
]

[project.urls]
Repository = "https://github.com/soda92/surun"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
ignore-vcs = true
packages = ["surun_tools"]
exclude = ["__pycache__", "*.pyc", "*.exe"]

[tool.hatch.build.targets.wheel]
ignore-vcs = true
packages = ["surun_tools"]
exclude = ["__pycache__", "*.pyc"]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "pytest>=8.3.5",
]

[project.scripts]
st = "stools.main:main"
