name: Build SuRun
on: pull_request

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Build debug
        run: pwsh build-debug.ps1

      - name: Build release
        run: pwsh build.ps1

      - name: Set timestamp
        id: timestamp
        run: |
          $now = Get-Date -Format "yyyyMMddHHmmss"
          echo "TIMESTAMP=$now" | Out-File -Path $env:GITHUB_ENV -Append

      - name: update artifact
        uses: actions/upload-artifact@v4
        with:
          name: surun-release-${{ env.TIMESTAMP }}
          path: |
            InstallSuRun.exe
            ReleaseUx64

      - uses: actions/upload-artifact@v4
        with:
          name: surun-debug-${{ env.TIMESTAMP }}
          path: |
            DebugUx64
            DebugU
