name: Build SuRun
on: pull_request

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Build debug
        run: pwsh scripts/build.ps1

      - name: Set timestamp
        id: timestamp
        run: |
          $now = Get-Date -Format "yyyyMMddHHmmss"
          echo "TIMESTAMP=$now" | Out-File -Path $env:GITHUB_ENV -Append

      - uses: actions/upload-artifact@v4
        with:
          name: surun-debug-${{ env.TIMESTAMP }}
          path: |
            PC/Debug
            PC/DebugUsr32
            PC/DebugUx64

