name: Build SuRun
on: pull_request

jobs:
  build:
    runs-on: windows-latest
    steps:
      - run: pwsh build.ps1
      - uses: actions/upload-artifact@v4
        with:
          path: InstallSuRun.exe

